// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: core.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const membership = `-- name: Membership :one
SELECT role FROM members WHERE household_id=$1 AND user_id=$2
`

type MembershipParams struct {
	HouseholdID pgtype.UUID
	UserID      pgtype.UUID
}

func (q *Queries) Membership(ctx context.Context, arg MembershipParams) (string, error) {
	row := q.db.QueryRow(ctx, membership, arg.HouseholdID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}
