// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthRateLimit struct {
	IpHash      string
	WindowStart pgtype.Timestamptz
	Attempts    int32
}

type Batch struct {
	ID            pgtype.UUID
	HouseholdID   pgtype.UUID
	IngredientID  pgtype.UUID
	QuantityMilli int64
	Location      string
	BoughtOn      pgtype.Date
	ExpiresOn     pgtype.Date
	ExpiryKind    string
	Source        string
	CreatedAt     pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	Condition     string
}

type BatchPurchaseCost struct {
	BatchID               pgtype.UUID
	HouseholdID           pgtype.UUID
	PurchaseQuantityMilli int64
	TotalCost             pgtype.Numeric
	Currency              string
	ActorID               pgtype.UUID
	RecordedAt            pgtype.Timestamptz
}

type BusinessEvent struct {
	ID          int64
	HouseholdID pgtype.UUID
	Kind        string
	CreatedAt   pgtype.Timestamptz
}

type CommunityPriceRecord struct {
	ID                  int64
	FamilyID            pgtype.UUID
	UserID              pgtype.UUID
	CityName            string
	IngredientCatalogID pgtype.UUID
	IngredientName      string
	StoreName           string
	Price               pgtype.Numeric
	PackageQuantity     pgtype.Numeric
	Unit                string
	SourceType          string
	PurchaseDate        pgtype.Date
	Visibility          string
	IdempotencyKey      string
	RequestHash         string
	CreatedAt           pgtype.Timestamptz
	NormalizedUnit      pgtype.Text
	NormalizedPrice     pgtype.Numeric
}

type CookingSession struct {
	ID          pgtype.UUID
	HouseholdID pgtype.UUID
	PlanMealID  pgtype.UUID
	CreatedBy   pgtype.UUID
	Status      string
	TargetAt    pgtype.Timestamptz
	StartsAt    pgtype.Timestamptz
	Schedule    []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type CookingStepProgress struct {
	SessionID   pgtype.UUID
	HouseholdID pgtype.UUID
	StepIndex   int32
	StartedAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
}

type Household struct {
	ID                  pgtype.UUID
	Name                string
	OwnerID             pgtype.UUID
	Servings            int32
	Preferences         string
	CreatedAt           pgtype.Timestamptz
	ExcludedIngredients []string
	Timezone            string
}

type Idempotency struct {
	HouseholdID pgtype.UUID
	Key         string
	RequestHash string
	Response    []byte
	CreatedAt   pgtype.Timestamptz
}

type Ingredient struct {
	ID           pgtype.UUID
	HouseholdID  pgtype.UUID
	Name         string
	Category     string
	Unit         string
	Dimension    string
	LowMilli     int64
	ImageKey     pgtype.Text
	ImageMime    pgtype.Text
	ImageVersion int64
	CatalogID    pgtype.UUID
	ArchivedAt   pgtype.Timestamptz
}

type IngredientCatalog struct {
	ID              pgtype.UUID
	Name            string
	Category        string
	DefaultUnit     string
	Aliases         []string
	IsDarkVegetable pgtype.Bool
}

type IngredientNutritionProfile struct {
	CatalogID pgtype.UUID
	Version   string
	Profile   []byte
	UpdatedAt pgtype.Timestamptz
}

type Invite struct {
	ID          pgtype.UUID
	HouseholdID pgtype.UUID
	Email       string
	Role        string
	CodeHash    string
	ExpiresAt   pgtype.Timestamptz
	AcceptedAt  pgtype.Timestamptz
}

type Job struct {
	ID              pgtype.UUID
	HouseholdID     pgtype.UUID
	Kind            string
	Status          string
	Payload         []byte
	Result          []byte
	Error           pgtype.Text
	Progress        int32
	Attempts        int32
	MaxAttempts     int32
	RunAt           pgtype.Timestamptz
	LeaseOwner      pgtype.Text
	LeaseToken      pgtype.UUID
	LeaseUntil      pgtype.Timestamptz
	CancelRequested bool
	CreatedBy       pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	RequestKey      pgtype.Text
	RequestHash     pgtype.Text
}

type JobEvent struct {
	ID        int64
	JobID     pgtype.UUID
	Event     string
	Detail    []byte
	CreatedAt pgtype.Timestamptz
}

type LocalPriceQuote struct {
	ID                   pgtype.UUID
	HouseholdID          pgtype.UUID
	IngredientName       string
	StoreName            string
	PackageQuantityMilli int64
	PackageUnit          string
	PriceMinor           int64
	Currency             string
	Latitude             pgtype.Float8
	Longitude            pgtype.Float8
	Source               string
	ObservedBy           pgtype.UUID
	ObservedAt           pgtype.Timestamptz
	City                 string
	Visibility           string
}

type MarketBenchmarkPrice struct {
	ID                  int64
	CityCode            string
	CityName            string
	IngredientCatalogID pgtype.UUID
	IngredientName      string
	Category            string
	Price               pgtype.Numeric
	Unit                string
	SourceAgency        string
	SourceUrl           string
	SourceItemName      string
	Specification       string
	PriceType           string
	RecordedDate        pgtype.Date
	PeriodStart         pgtype.Date
	CollectedAt         pgtype.Timestamptz
}

type MealCompletion struct {
	ID          pgtype.UUID
	HouseholdID pgtype.UUID
	PlanMealID  pgtype.UUID
	Day         pgtype.Date
	Meal        string
	ActorID     pgtype.UUID
	CompletedAt pgtype.Timestamptz
}

type MealCompletionSnapshot struct {
	CompletionID pgtype.UUID
	HouseholdID  pgtype.UUID
	Servings     int32
	Timezone     string
	Dishes       []byte
	CapturedAt   pgtype.Timestamptz
}

type Member struct {
	HouseholdID pgtype.UUID
	UserID      pgtype.UUID
	Role        string
}

type MultiMealProposal struct {
	ID           pgtype.UUID
	HouseholdID  pgtype.UUID
	CreatedBy    pgtype.UUID
	Request      []byte
	Result       []byte
	SnapshotHash string
	Status       string
	PlanID       pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
}

type PantryConsumption struct {
	ID             pgtype.UUID
	HouseholdID    pgtype.UUID
	PantryID       pgtype.UUID
	PlanMealID     pgtype.UUID
	LedgerID       pgtype.UUID
	RequestedMilli int64
	DeductedMilli  int64
	Unit           string
	Basis          []byte
	CreatedAt      pgtype.Timestamptz
}

type Plan struct {
	ID                  pgtype.UUID
	HouseholdID         pgtype.UUID
	Status              string
	Revision            int32
	CreatedBy           pgtype.UUID
	CreatedAt           pgtype.Timestamptz
	ConfirmedAt         pgtype.Timestamptz
	ExcludedIngredients []string
}

type PlanMeal struct {
	ID       pgtype.UUID
	PlanID   pgtype.UUID
	Day      pgtype.Date
	Meal     string
	Servings int32
	RecipeID pgtype.UUID
}

type PlanMealDish struct {
	ID         pgtype.UUID
	PlanMealID pgtype.UUID
	RecipeID   pgtype.UUID
}

type Recipe struct {
	ID       pgtype.UUID
	Title    string
	Servings int32
	Minutes  int32
	Tags     []string
	Steps    []string
	Source   string
}

type RecipeItem struct {
	RecipeID      pgtype.UUID
	Name          string
	QuantityMilli int64
	Unit          string
	CatalogID     pgtype.UUID
}

type RecipeSeasoning struct {
	RecipeID    pgtype.UUID
	Name        string
	DoseUnit    string
	DoseMilli   int64
	IsSeasoning bool
}

type RecipeStep struct {
	RecipeID         pgtype.UUID
	Ordinal          int32
	Version          int32
	Action           string
	Kind             string
	DurationSeconds  int32
	Dependencies     []int32
	Equipment        string
	IsParallelizable bool
	Source           string
}

type Reminder struct {
	ID          pgtype.UUID
	HouseholdID pgtype.UUID
	UserID      pgtype.UUID
	BatchID     pgtype.UUID
	DueOn       pgtype.Date
	ReadAt      pgtype.Timestamptz
}

type SeasoningConversion struct {
	Name         string
	DoseUnit     string
	Unit         string
	PerDoseMilli int64
	Source       string
}

type Session struct {
	TokenHash string
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

type ShoppingItem struct {
	ID                 pgtype.UUID
	ListID             pgtype.UUID
	Name               string
	Unit               string
	NeededMilli        int64
	BoughtMilli        int64
	Checked            bool
	Stocked            bool
	Origin             string
	SourceIngredientID pgtype.UUID
	DeletedAt          pgtype.Timestamptz
}

type ShoppingList struct {
	ID          pgtype.UUID
	HouseholdID pgtype.UUID
	PlanID      pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	Source      string
}

type SmsChallenge struct {
	ID        pgtype.UUID
	Phone     string
	Purpose   string
	Actor     string
	CodeHash  string
	State     string
	ExpiresAt pgtype.Timestamptz
	Attempts  int32
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type SmsSendLimit struct {
	Phone    string
	LastSent pgtype.Timestamptz
	Day      pgtype.Date
	Count    int32
}

type StockCostSnapshot struct {
	LedgerID      pgtype.UUID
	HouseholdID   pgtype.UUID
	AllocatedCost pgtype.Numeric
	Currency      string
}

type StockLedger struct {
	ID          pgtype.UUID
	HouseholdID pgtype.UUID
	BatchID     pgtype.UUID
	DeltaMilli  int64
	Reason      string
	ActorID     pgtype.UUID
	RefType     pgtype.Text
	RefID       pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	Note        string
	IsEstimated bool
}

type StockLedgerSnapshot struct {
	LedgerID         pgtype.UUID
	HouseholdID      pgtype.UUID
	IngredientID     pgtype.UUID
	IngredientName   string
	Category         string
	Unit             string
	Dimension        string
	ExpiresAt        pgtype.Timestamptz
	ExpiryKind       string
	IsDarkVegetable  pgtype.Bool
	NutritionProfile []byte
	NutritionVersion pgtype.Text
	CapturedAt       pgtype.Timestamptz
}

type User struct {
	ID            pgtype.UUID
	Email         pgtype.Text
	PasswordHash  string
	Name          string
	Timezone      string
	RemindDays    int32
	CreatedAt     pgtype.Timestamptz
	Phone         pgtype.Text
	PhoneVerified bool
}

type VirtualPantry struct {
	ID                pgtype.UUID
	HouseholdID       pgtype.UUID
	BatchID           pgtype.UUID
	Name              string
	CapacityMilli     int64
	AlertThresholdPct int32
	Active            bool
	AcceptedBy        pgtype.UUID
	AcceptedAt        pgtype.Timestamptz
}
