// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: multi_meal.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const lockMultiMealProposal = `-- name: LockMultiMealProposal :one
SELECT id, household_id, created_by, request, result, snapshot_hash, status, plan_id, created_at, expires_at FROM multi_meal_proposals WHERE id=$1 AND household_id=$2 FOR UPDATE
`

type LockMultiMealProposalParams struct {
	ID          pgtype.UUID
	HouseholdID pgtype.UUID
}

func (q *Queries) LockMultiMealProposal(ctx context.Context, arg LockMultiMealProposalParams) (MultiMealProposal, error) {
	row := q.db.QueryRow(ctx, lockMultiMealProposal, arg.ID, arg.HouseholdID)
	var i MultiMealProposal
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.CreatedBy,
		&i.Request,
		&i.Result,
		&i.SnapshotHash,
		&i.Status,
		&i.PlanID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
