// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pantry.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const lockPantryBatch = `-- name: LockPantryBatch :one
SELECT p.id,p.batch_id,p.name,p.capacity_milli,p.alert_threshold_pct,p.active,
 b.quantity_milli,b.condition,b.expires_at,b.ingredient_id,i.unit
FROM virtual_pantry p JOIN batches b ON b.id=p.batch_id AND b.household_id=p.household_id
JOIN ingredients i ON i.id=b.ingredient_id AND i.household_id=b.household_id
WHERE p.id=$1 AND p.household_id=$2 FOR UPDATE OF b,p
`

type LockPantryBatchParams struct {
	ID          pgtype.UUID
	HouseholdID pgtype.UUID
}

type LockPantryBatchRow struct {
	ID                pgtype.UUID
	BatchID           pgtype.UUID
	Name              string
	CapacityMilli     int64
	AlertThresholdPct int32
	Active            bool
	QuantityMilli     int64
	Condition         string
	ExpiresAt         pgtype.Timestamptz
	IngredientID      pgtype.UUID
	Unit              string
}

func (q *Queries) LockPantryBatch(ctx context.Context, arg LockPantryBatchParams) (LockPantryBatchRow, error) {
	row := q.db.QueryRow(ctx, lockPantryBatch, arg.ID, arg.HouseholdID)
	var i LockPantryBatchRow
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.Name,
		&i.CapacityMilli,
		&i.AlertThresholdPct,
		&i.Active,
		&i.QuantityMilli,
		&i.Condition,
		&i.ExpiresAt,
		&i.IngredientID,
		&i.Unit,
	)
	return i, err
}
