// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pipeline.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCookingSession = `-- name: GetCookingSession :one
SELECT id, household_id, plan_meal_id, created_by, status, target_at, starts_at, schedule, created_at, updated_at FROM cooking_sessions WHERE id=$1 AND household_id=$2
`

type GetCookingSessionParams struct {
	ID          pgtype.UUID
	HouseholdID pgtype.UUID
}

func (q *Queries) GetCookingSession(ctx context.Context, arg GetCookingSessionParams) (CookingSession, error) {
	row := q.db.QueryRow(ctx, getCookingSession, arg.ID, arg.HouseholdID)
	var i CookingSession
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.PlanMealID,
		&i.CreatedBy,
		&i.Status,
		&i.TargetAt,
		&i.StartsAt,
		&i.Schedule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecipeSteps = `-- name: GetRecipeSteps :many
SELECT rs.recipe_id, rs.ordinal, rs.version, rs.action, rs.kind, rs.duration_seconds, rs.dependencies, rs.equipment, rs.is_parallelizable, rs.source,r.title FROM recipe_steps rs JOIN recipes r ON r.id=rs.recipe_id
WHERE rs.recipe_id=ANY($1::uuid[]) ORDER BY rs.recipe_id,rs.ordinal
`

type GetRecipeStepsRow struct {
	RecipeID         pgtype.UUID
	Ordinal          int32
	Version          int32
	Action           string
	Kind             string
	DurationSeconds  int32
	Dependencies     []int32
	Equipment        string
	IsParallelizable bool
	Source           string
	Title            string
}

func (q *Queries) GetRecipeSteps(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetRecipeStepsRow, error) {
	rows, err := q.db.Query(ctx, getRecipeSteps, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecipeStepsRow
	for rows.Next() {
		var i GetRecipeStepsRow
		if err := rows.Scan(
			&i.RecipeID,
			&i.Ordinal,
			&i.Version,
			&i.Action,
			&i.Kind,
			&i.DurationSeconds,
			&i.Dependencies,
			&i.Equipment,
			&i.IsParallelizable,
			&i.Source,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
