// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prices.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findPriceIngredient = `-- name: FindPriceIngredient :one
SELECT id,name FROM ingredient_catalog WHERE name=$1 OR $1=ANY(aliases) ORDER BY (name=$1) DESC,name LIMIT 1
`

type FindPriceIngredientRow struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) FindPriceIngredient(ctx context.Context, name string) (FindPriceIngredientRow, error) {
	row := q.db.QueryRow(ctx, findPriceIngredient, name)
	var i FindPriceIngredientRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getLatestBenchmarkPrice = `-- name: GetLatestBenchmarkPrice :many
SELECT DISTINCT ON (source_agency,source_item_name,specification,price_type,unit) b.id, b.city_code, b.city_name, b.ingredient_catalog_id, b.ingredient_name, b.category, b.price, b.unit, b.source_agency, b.source_url, b.source_item_name, b.specification, b.price_type, b.recorded_date, b.period_start, b.collected_at,
 COALESCE((SELECT p.price::text FROM market_benchmark_prices p
 WHERE p.city_code=b.city_code AND p.ingredient_catalog_id=b.ingredient_catalog_id
 AND p.source_agency=b.source_agency AND p.source_item_name=b.source_item_name
 AND p.specification=b.specification AND p.price_type=b.price_type AND p.unit=b.unit
 AND p.recorded_date=b.recorded_date-7 AND p.period_start=b.period_start-7 LIMIT 1),'')::text AS previous_price
FROM market_benchmark_prices b WHERE b.city_name=$1 AND b.ingredient_name=$2
ORDER BY source_agency,source_item_name,specification,price_type,unit,recorded_date DESC
`

type GetLatestBenchmarkPriceParams struct {
	CityName       string
	IngredientName string
}

type GetLatestBenchmarkPriceRow struct {
	ID                  int64
	CityCode            string
	CityName            string
	IngredientCatalogID pgtype.UUID
	IngredientName      string
	Category            string
	Price               pgtype.Numeric
	Unit                string
	SourceAgency        string
	SourceUrl           string
	SourceItemName      string
	Specification       string
	PriceType           string
	RecordedDate        pgtype.Date
	PeriodStart         pgtype.Date
	CollectedAt         pgtype.Timestamptz
	PreviousPrice       string
}

func (q *Queries) GetLatestBenchmarkPrice(ctx context.Context, arg GetLatestBenchmarkPriceParams) ([]GetLatestBenchmarkPriceRow, error) {
	rows, err := q.db.Query(ctx, getLatestBenchmarkPrice, arg.CityName, arg.IngredientName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestBenchmarkPriceRow
	for rows.Next() {
		var i GetLatestBenchmarkPriceRow
		if err := rows.Scan(
			&i.ID,
			&i.CityCode,
			&i.CityName,
			&i.IngredientCatalogID,
			&i.IngredientName,
			&i.Category,
			&i.Price,
			&i.Unit,
			&i.SourceAgency,
			&i.SourceUrl,
			&i.SourceItemName,
			&i.Specification,
			&i.PriceType,
			&i.RecordedDate,
			&i.PeriodStart,
			&i.CollectedAt,
			&i.PreviousPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBenchmarkPricesByCity = `-- name: ListBenchmarkPricesByCity :many
SELECT DISTINCT ON (ingredient_name,source_agency,source_item_name,specification,price_type,unit) id, city_code, city_name, ingredient_catalog_id, ingredient_name, category, price, unit, source_agency, source_url, source_item_name, specification, price_type, recorded_date, period_start, collected_at
FROM market_benchmark_prices WHERE city_name=$1 AND ($2::text='' OR category=$2)
ORDER BY ingredient_name,source_agency,source_item_name,specification,price_type,unit,recorded_date DESC
`

type ListBenchmarkPricesByCityParams struct {
	CityName string
	Column2  string
}

func (q *Queries) ListBenchmarkPricesByCity(ctx context.Context, arg ListBenchmarkPricesByCityParams) ([]MarketBenchmarkPrice, error) {
	rows, err := q.db.Query(ctx, listBenchmarkPricesByCity, arg.CityName, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarketBenchmarkPrice
	for rows.Next() {
		var i MarketBenchmarkPrice
		if err := rows.Scan(
			&i.ID,
			&i.CityCode,
			&i.CityName,
			&i.IngredientCatalogID,
			&i.IngredientName,
			&i.Category,
			&i.Price,
			&i.Unit,
			&i.SourceAgency,
			&i.SourceUrl,
			&i.SourceItemName,
			&i.Specification,
			&i.PriceType,
			&i.RecordedDate,
			&i.PeriodStart,
			&i.CollectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOfficialPrice = `-- name: UpsertOfficialPrice :execrows
INSERT INTO market_benchmark_prices(city_code,city_name,ingredient_catalog_id,ingredient_name,category,price,unit,source_agency,source_url,source_item_name,specification,price_type,recorded_date,period_start)
SELECT '110100','北京市',id,name,category,$1::numeric,'500g','北京市价格监测中心','https://www.beijingprice.cn/mrjg/',$2::text,$3::text,'retail_monitor',$4::date,$4::date
FROM ingredient_catalog WHERE name=$5::text
ON CONFLICT(city_code,ingredient_catalog_id,source_agency,source_item_name,specification,price_type,unit,recorded_date)
DO UPDATE SET price=EXCLUDED.price,collected_at=now()
`

type UpsertOfficialPriceParams struct {
	Price         pgtype.Numeric
	SourceItem    string
	Specification string
	Day           pgtype.Date
	Ingredient    string
}

func (q *Queries) UpsertOfficialPrice(ctx context.Context, arg UpsertOfficialPriceParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertOfficialPrice,
		arg.Price,
		arg.SourceItem,
		arg.Specification,
		arg.Day,
		arg.Ingredient,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertRegionalPrice = `-- name: UpsertRegionalPrice :execrows
INSERT INTO market_benchmark_prices(city_code,city_name,ingredient_catalog_id,ingredient_name,category,price,unit,source_agency,source_url,source_item_name,specification,price_type,recorded_date,period_start)
SELECT $1::text,$2::text,id,name,category,$3::numeric,$4::text,$5::text,$6::text,$7::text,$8::text,'retail_monitor',$9::date,$10::date
FROM ingredient_catalog WHERE name=$11::text
ON CONFLICT(city_code,ingredient_catalog_id,source_agency,source_item_name,specification,price_type,unit,recorded_date)
DO UPDATE SET price=EXCLUDED.price,source_url=EXCLUDED.source_url,collected_at=now()
`

type UpsertRegionalPriceParams struct {
	CityCode      string
	City          string
	Price         pgtype.Numeric
	Unit          string
	Agency        string
	SourceUrl     string
	Original      string
	Specification string
	Day           pgtype.Date
	PeriodStart   pgtype.Date
	Ingredient    string
}

func (q *Queries) UpsertRegionalPrice(ctx context.Context, arg UpsertRegionalPriceParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertRegionalPrice,
		arg.CityCode,
		arg.City,
		arg.Price,
		arg.Unit,
		arg.Agency,
		arg.SourceUrl,
		arg.Original,
		arg.Specification,
		arg.Day,
		arg.PeriodStart,
		arg.Ingredient,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
