// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: v11.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const lockMealForCooking = `-- name: LockMealForCooking :one
SELECT p.status, pm.day::text AS day, pm.meal
FROM plan_meals pm JOIN plans p ON p.id=pm.plan_id
WHERE pm.id=$1 AND pm.plan_id=$2 AND p.household_id=$3
FOR UPDATE OF p
`

type LockMealForCookingParams struct {
	ID          pgtype.UUID
	PlanID      pgtype.UUID
	HouseholdID pgtype.UUID
}

type LockMealForCookingRow struct {
	Status string
	Day    string
	Meal   string
}

func (q *Queries) LockMealForCooking(ctx context.Context, arg LockMealForCookingParams) (LockMealForCookingRow, error) {
	row := q.db.QueryRow(ctx, lockMealForCooking, arg.ID, arg.PlanID, arg.HouseholdID)
	var i LockMealForCookingRow
	err := row.Scan(&i.Status, &i.Day, &i.Meal)
	return i, err
}
