// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: v2.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBatchCost = `-- name: GetBatchCost :one
SELECT total_cost::text AS total_cost,currency,purchase_quantity_milli,recorded_at
FROM batch_purchase_costs WHERE batch_id=$1 AND household_id=$2
`

type GetBatchCostParams struct {
	BatchID     pgtype.UUID
	HouseholdID pgtype.UUID
}

type GetBatchCostRow struct {
	TotalCost             string
	Currency              string
	PurchaseQuantityMilli int64
	RecordedAt            pgtype.Timestamptz
}

func (q *Queries) GetBatchCost(ctx context.Context, arg GetBatchCostParams) (GetBatchCostRow, error) {
	row := q.db.QueryRow(ctx, getBatchCost, arg.BatchID, arg.HouseholdID)
	var i GetBatchCostRow
	err := row.Scan(
		&i.TotalCost,
		&i.Currency,
		&i.PurchaseQuantityMilli,
		&i.RecordedAt,
	)
	return i, err
}

const getMealCompletionSnapshot = `-- name: GetMealCompletionSnapshot :one
SELECT s.completion_id,s.servings,s.timezone,s.dishes,s.captured_at
FROM meal_completion_snapshots s
JOIN meal_completions mc ON mc.id=s.completion_id
WHERE s.household_id=$1 AND mc.plan_meal_id=$2
`

type GetMealCompletionSnapshotParams struct {
	HouseholdID pgtype.UUID
	PlanMealID  pgtype.UUID
}

type GetMealCompletionSnapshotRow struct {
	CompletionID pgtype.UUID
	Servings     int32
	Timezone     string
	Dishes       []byte
	CapturedAt   pgtype.Timestamptz
}

func (q *Queries) GetMealCompletionSnapshot(ctx context.Context, arg GetMealCompletionSnapshotParams) (GetMealCompletionSnapshotRow, error) {
	row := q.db.QueryRow(ctx, getMealCompletionSnapshot, arg.HouseholdID, arg.PlanMealID)
	var i GetMealCompletionSnapshotRow
	err := row.Scan(
		&i.CompletionID,
		&i.Servings,
		&i.Timezone,
		&i.Dishes,
		&i.CapturedAt,
	)
	return i, err
}

const lockBatchForCost = `-- name: LockBatchForCost :one
SELECT id FROM batches WHERE id=$1 AND household_id=$2 FOR UPDATE
`

type LockBatchForCostParams struct {
	ID          pgtype.UUID
	HouseholdID pgtype.UUID
}

func (q *Queries) LockBatchForCost(ctx context.Context, arg LockBatchForCostParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockBatchForCost, arg.ID, arg.HouseholdID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
