-- +goose Up
CREATE TABLE users (id uuid PRIMARY KEY, email text NOT NULL UNIQUE, password_hash text NOT NULL, name text NOT NULL, timezone text NOT NULL DEFAULT 'Asia/Shanghai', remind_days int NOT NULL DEFAULT 3 CHECK (remind_days BETWEEN 0 AND 30), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE sessions (token_hash text PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at timestamptz NOT NULL);
CREATE TABLE households (id uuid PRIMARY KEY, name text NOT NULL, owner_id uuid NOT NULL REFERENCES users(id), servings int NOT NULL DEFAULT 2 CHECK(servings BETWEEN 1 AND 20), preferences text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE members (household_id uuid NOT NULL REFERENCES households(id) ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, role text NOT NULL CHECK(role IN ('owner','editor','viewer')), PRIMARY KEY(household_id,user_id));
CREATE TABLE invites (id uuid PRIMARY KEY, household_id uuid NOT NULL REFERENCES households(id) ON DELETE CASCADE, email text NOT NULL, role text NOT NULL CHECK(role IN ('editor','viewer')), code_hash text NOT NULL UNIQUE, expires_at timestamptz NOT NULL, accepted_at timestamptz);
CREATE TABLE ingredients (id uuid PRIMARY KEY, household_id uuid NOT NULL REFERENCES households(id) ON DELETE CASCADE, name text NOT NULL, category text NOT NULL DEFAULT '', unit text NOT NULL, dimension text NOT NULL CHECK(dimension IN ('mass','volume','count')), low_milli bigint NOT NULL DEFAULT 0 CHECK(low_milli>=0), UNIQUE(household_id,name,unit));
CREATE TABLE batches (id uuid PRIMARY KEY, household_id uuid NOT NULL REFERENCES households(id) ON DELETE CASCADE, ingredient_id uuid NOT NULL REFERENCES ingredients(id), quantity_milli bigint NOT NULL DEFAULT 0 CHECK(quantity_milli>=0), location text NOT NULL DEFAULT '', bought_on date, expires_on date, expiry_kind text NOT NULL DEFAULT 'unknown' CHECK(expiry_kind IN ('label','user','estimate','unknown')), source text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX batches_fefo ON batches(household_id,ingredient_id,expires_on) WHERE quantity_milli>0;
CREATE TABLE stock_ledger (id uuid PRIMARY KEY, household_id uuid NOT NULL REFERENCES households(id), batch_id uuid NOT NULL REFERENCES batches(id), delta_milli bigint NOT NULL CHECK(delta_milli<>0), reason text NOT NULL CHECK(reason IN ('purchase','consume','waste','correction','manual')), actor_id uuid REFERENCES users(id), ref_type text, ref_id uuid, created_at timestamptz NOT NULL DEFAULT now());
CREATE FUNCTION prevent_stock_ledger_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'stock ledger is append only'; END $$;
CREATE TRIGGER stock_ledger_immutable BEFORE UPDATE OR DELETE ON stock_ledger FOR EACH ROW EXECUTE FUNCTION prevent_stock_ledger_mutation();
CREATE TABLE recipes (id uuid PRIMARY KEY, title text NOT NULL, servings int NOT NULL CHECK(servings>0), minutes int NOT NULL CHECK(minutes>0), tags text[] NOT NULL DEFAULT '{}', steps text[] NOT NULL, source text NOT NULL);
CREATE TABLE recipe_items (recipe_id uuid NOT NULL REFERENCES recipes(id) ON DELETE CASCADE, name text NOT NULL, quantity_milli bigint NOT NULL CHECK(quantity_milli>0), unit text NOT NULL, PRIMARY KEY(recipe_id,name,unit));
CREATE TABLE plans (id uuid PRIMARY KEY, household_id uuid NOT NULL REFERENCES households(id), status text NOT NULL CHECK(status IN ('draft','confirmed','consumed','rejected','cancelled')), revision int NOT NULL DEFAULT 1, created_by uuid NOT NULL REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), confirmed_at timestamptz);
CREATE TABLE plan_meals (id uuid PRIMARY KEY, plan_id uuid NOT NULL REFERENCES plans(id) ON DELETE CASCADE, day date NOT NULL, meal text NOT NULL CHECK(meal IN ('breakfast','lunch','dinner')), servings int NOT NULL CHECK(servings BETWEEN 1 AND 20), recipe_id uuid NOT NULL REFERENCES recipes(id), UNIQUE(plan_id,day,meal));
CREATE TABLE shopping_lists (id uuid PRIMARY KEY, household_id uuid NOT NULL REFERENCES households(id), plan_id uuid NOT NULL UNIQUE REFERENCES plans(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE shopping_items (id uuid PRIMARY KEY, list_id uuid NOT NULL REFERENCES shopping_lists(id) ON DELETE CASCADE, name text NOT NULL, unit text NOT NULL, needed_milli bigint NOT NULL CHECK(needed_milli>0), bought_milli bigint NOT NULL DEFAULT 0 CHECK(bought_milli>=0), checked boolean NOT NULL DEFAULT false, stocked boolean NOT NULL DEFAULT false, UNIQUE(list_id,name,unit));
CREATE TABLE idempotency (household_id uuid NOT NULL REFERENCES households(id), key text NOT NULL, request_hash text NOT NULL, response jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(household_id,key));
CREATE TABLE jobs (id uuid PRIMARY KEY, household_id uuid NOT NULL REFERENCES households(id), kind text NOT NULL CHECK(kind IN ('plan','reminder','image')), status text NOT NULL CHECK(status IN ('queued','running','awaiting_confirmation','succeeded','failed','cancelled')), payload jsonb NOT NULL, result jsonb, error text, progress int NOT NULL DEFAULT 0, attempts int NOT NULL DEFAULT 0, max_attempts int NOT NULL DEFAULT 3, run_at timestamptz NOT NULL DEFAULT now(), lease_owner text, lease_token uuid, lease_until timestamptz, cancel_requested boolean NOT NULL DEFAULT false, created_by uuid NOT NULL REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX jobs_claim ON jobs(run_at,created_at) WHERE status IN ('queued','running');
CREATE TABLE job_events (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, job_id uuid NOT NULL REFERENCES jobs(id) ON DELETE CASCADE, event text NOT NULL, detail jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE reminders (id uuid PRIMARY KEY, household_id uuid NOT NULL REFERENCES households(id), user_id uuid NOT NULL REFERENCES users(id), batch_id uuid NOT NULL REFERENCES batches(id), due_on date NOT NULL, read_at timestamptz, UNIQUE(user_id,batch_id,due_on));
-- +goose Down
DROP TABLE reminders, job_events, jobs, idempotency, shopping_items, shopping_lists, plan_meals, plans, recipe_items, recipes, stock_ledger, batches, ingredients, invites, members, households, sessions, users;
DROP FUNCTION prevent_stock_ledger_mutation;
