package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

const knowledgePath = "docs/generated/contracts.md"

// Facts are extracted from source rather than copied into a second manifest.
func knowledge(root string, update bool) error {
	generated, err := contractInventory(root)
	if err != nil {
		return err
	}
	path := filepath.Join(root, knowledgePath)
	if update {
		if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
			return err
		}
		if err := os.WriteFile(path, generated, 0644); err != nil {
			return err
		}
	} else {
		actual, err := os.ReadFile(path)
		if err != nil || !bytes.Equal(bytes.ReplaceAll(actual, []byte("\r\n"), []byte("\n")), generated) {
			return fmt.Errorf("source inventory drift: run go run ./cmd/harness -mode knowledge -update, then review %s", knowledgePath)
		}
	}
	return documentationLinks(root)
}

func contractInventory(root string) ([]byte, error) {
	var out strings.Builder
	out.WriteString("# Generated source inventory\n\nGenerated by `go run ./cmd/harness -mode knowledge -update`. Do not edit manually. CI compares this file with current source. This checks factual inventory and local links; it does not prove all prose is correct.\n\n")
	section := func(title string, rows []string) {
		sort.Strings(rows)
		out.WriteString("## " + title + "\n\n")
		for _, row := range rows {
			out.WriteString("- `" + row + "`\n")
		}
		out.WriteString("\n")
	}
	var routes []string
	for _, file := range []string{"internal/app/app.go", "internal/insights/http.go"} {
		f, err := parser.ParseFile(token.NewFileSet(), filepath.Join(root, file), nil, 0)
		if err != nil {
			return nil, err
		}
		// Fail rather than silently miss a changed group prefix.
		prefix := map[string]string{"r": "", "mux": ""}
		var scanErr error
		ast.Inspect(f, func(n ast.Node) bool {
			assign, ok := n.(*ast.AssignStmt)
			if ok && len(assign.Lhs) == 1 && len(assign.Rhs) == 1 {
				id, _ := assign.Lhs[0].(*ast.Ident)
				call, _ := assign.Rhs[0].(*ast.CallExpr)
				if id != nil && call != nil {
					if sel, ok := call.Fun.(*ast.SelectorExpr); ok && sel.Sel.Name == "Group" && len(call.Args) > 0 {
						if recv, ok := sel.X.(*ast.Ident); ok {
							base, found := prefix[recv.Name]
							p, err := stringLiteral(call.Args[0])
							if !found || err != nil {
								scanErr = fmt.Errorf("unresolved route group in %s", file)
							} else {
								prefix[id.Name] = base + p
							}
						}
					}
				}
			}
			call, ok := n.(*ast.CallExpr)
			if !ok || len(call.Args) == 0 {
				return true
			}
			sel, ok := call.Fun.(*ast.SelectorExpr)
			if !ok {
				return true
			}
			recv, ok := sel.X.(*ast.Ident)
			if !ok {
				return true
			}
			method := sel.Sel.Name
			if !strings.Contains("|GET|POST|PATCH|DELETE|PUT|HandleFunc|", "|"+method+"|") {
				return true
			}
			p, err := stringLiteral(call.Args[0])
			base, found := prefix[recv.Name]
			if err != nil || !found {
				scanErr = fmt.Errorf("unresolved route %s.%s in %s", recv.Name, method, file)
				return true
			}
			if method == "HandleFunc" {
				routes = append(routes, p+" (insights)")
			} else {
				routes = append(routes, method+" "+base+p+" (api)")
			}
			return true
		})
		if scanErr != nil {
			return nil, scanErr
		}
	}
	section("HTTP routes", routes)
	gomod, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		return nil, err
	}
	var deps []string
	for _, line := range strings.Split(string(gomod), "\n") {
		fields := strings.Fields(line)
		if len(fields) == 2 && (fields[0] == "go" || strings.HasPrefix(fields[1], "v")) {
			deps = append(deps, strings.Join(fields, " "))
		}
	}
	section("Go version and direct dependencies", deps)
	var pkg struct {
		Dependencies    map[string]string `json:"dependencies"`
		DevDependencies map[string]string `json:"devDependencies"`
	}
	raw, err := os.ReadFile(filepath.Join(root, "web/package.json"))
	if err != nil {
		return nil, err
	}
	if err := json.Unmarshal(raw, &pkg); err != nil {
		return nil, err
	}
	deps = nil
	for name, version := range pkg.Dependencies {
		deps = append(deps, name+" "+version)
	}
	for name, version := range pkg.DevDependencies {
		deps = append(deps, name+" "+version+" (dev)")
	}
	section("Frontend dependencies", deps)
	raw, err = os.ReadFile(filepath.Join(root, ".env.example"))
	if err != nil {
		return nil, err
	}
	var keys []string
	for _, line := range strings.Split(string(raw), "\n") {
		if key, _, ok := strings.Cut(line, "="); ok && regexp.MustCompile(`^[A-Z][A-Z0-9_]*$`).MatchString(key) {
			keys = append(keys, key) // Never include example or real secret values.
		}
	}
	section("Documented configuration keys", keys)
	var services []string
	for _, file := range []string{"compose.acceptance.yaml", "compose.platform.yaml", "compose.trial.yaml", "compose.trial-deepseek.yaml", "compose.learning.yaml", "compose.restore.yaml"} {
		raw, err := os.ReadFile(filepath.Join(root, file))
		if err != nil {
			return nil, err
		}
		var cfg struct {
			Services map[string]struct {
				Image string `yaml:"image"`
			} `yaml:"services"`
		}
		if err := yaml.Unmarshal(raw, &cfg); err != nil {
			return nil, err
		}
		for name, service := range cfg.Services {
			services = append(services, file+": "+name+" / "+service.Image)
		}
	}
	section("Deployment services and images", services)
	files, err := filepath.Glob(filepath.Join(root, "sql/schema/*.sql"))
	if err != nil {
		return nil, err
	}
	var migrations []string
	for _, file := range files {
		raw, err := os.ReadFile(file)
		if err != nil {
			return nil, err
		}
		digest := sha256.Sum256(bytes.ReplaceAll(raw, []byte("\r\n"), []byte("\n")))
		migrations = append(migrations, fmt.Sprintf("%s sha256:%x", filepath.Base(file), digest))
	}
	section("Kitchen migrations", migrations)
	f, err := parser.ParseFile(token.NewFileSet(), filepath.Join(root, "internal/events/stock.go"), nil, 0)
	if err != nil {
		return nil, err
	}
	var fields []string
	ast.Inspect(f, func(n ast.Node) bool {
		if spec, ok := n.(*ast.ValueSpec); ok && len(spec.Names) == 1 && spec.Names[0].Name == "StockTopic" && len(spec.Values) == 1 {
			value, err := stringLiteral(spec.Values[0])
			if err == nil {
				fields = append(fields, "topic: "+value)
			}
		}
		if spec, ok := n.(*ast.TypeSpec); ok && spec.Name.Name == "Stock" {
			if st, ok := spec.Type.(*ast.StructType); ok {
				for _, field := range st.Fields.List {
					if field.Tag != nil {
						tag, _ := strconv.Unquote(field.Tag.Value)
						var typ strings.Builder
						_ = printer.Fprint(&typ, token.NewFileSet(), field.Type)
						fields = append(fields, field.Names[0].Name+" "+typ.String()+" "+tag)
					}
				}
			}
		}
		return true
	})
	section("Stock event JSON contract", fields)
	return []byte(strings.TrimRight(out.String(), "\n") + "\n"), nil
}

func stringLiteral(expr ast.Expr) (string, error) {
	lit, ok := expr.(*ast.BasicLit)
	if !ok || lit.Kind != token.STRING {
		return "", fmt.Errorf("expected string literal")
	}
	return strconv.Unquote(lit.Value)
}

var localLink = regexp.MustCompile(`\[[^\]\n]*\]\(([^)\n]+)\)`)

func documentationLinks(root string) error {
	files := []string{"README.md", "AGENTS.md", "ARCHITECTURE.md"}
	for _, optional := range []string{"CONTRIBUTING.md", "SECURITY.md", "CHANGELOG.md"} {
		if _, err := os.Stat(filepath.Join(root, optional)); err == nil {
			files = append(files, optional)
		}
	}
	err := filepath.WalkDir(filepath.Join(root, "docs"), func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() && strings.HasSuffix(path, ".md") {
			rel, _ := filepath.Rel(root, path)
			files = append(files, rel)
		}
		return nil
	})
	if err != nil {
		return err
	}
	for _, file := range files {
		raw, err := os.ReadFile(filepath.Join(root, file))
		if err != nil {
			return err
		}
		for _, link := range localLink.FindAllStringSubmatch(string(raw), -1) {
			target := strings.Trim(link[1], "<>")
			if strings.Contains(target, "://") || strings.HasPrefix(target, "#") || strings.HasPrefix(target, "mailto:") {
				continue
			}
			target, _, _ = strings.Cut(target, "#")
			path := filepath.Clean(filepath.Join(root, filepath.Dir(file), target))
			rel, _ := filepath.Rel(root, path)
			if rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) || filepath.IsAbs(target) {
				return fmt.Errorf("%s: local link escapes repository: %s", file, target)
			}
			if _, err := os.Stat(path); err != nil {
				return fmt.Errorf("%s: broken local link %s", file, target)
			}
		}
	}
	return nil
}
