import {useState,useEffect} from 'react'
import {useQuery,useQueryClient} from '@tanstack/react-query'
import {api} from './api'
import {useUI} from './store'
import {Button,Card,Field,Notice} from './ui'

export function SMSCode({phone,purpose,token='',onChallenge,code,onCode}:{phone:string;purpose:'login'|'register'|'bind';token?:string;onChallenge:(id:string)=>void;code:string;onCode:(v:string)=>void}){
 const capability=useQuery({queryKey:['sms-capabilities'],queryFn:()=>api<{sms_enabled:boolean}>('/auth/capabilities','')})
 const [until,setUntil]=useState(0),[now,setNow]=useState(Date.now()),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const seconds=Math.max(0,Math.ceil((until-now)/1000))
 useEffect(()=>{if(!until)return;const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[until])
 async function send(){setBusy(true);setError('');try{const r=await api<{challenge_id:string;retry_after:number}>(purpose==='bind'?'/me/phone/code':'/auth/sms/code',token,'POST',{phone,purpose});onChallenge(r.challenge_id);setUntil(Date.now()+r.retry_after*1000);setNow(Date.now())}catch(e){setError(String(e))}finally{setBusy(false)}}
 return <div className="space-y-2"><div className="flex items-end gap-2"><div className="min-w-0 flex-1"><Field label="短信验证码" inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={e=>onCode(e.target.value)} required/></div><Button type="button" variant="outline" disabled={busy||seconds>0||!capability.data?.sms_enabled||!phone.trim()} onClick={send}>{busy?'发送中…':seconds?seconds+'秒后重发':'获取验证码'}</Button></div>{capability.isLoading&&<p className="text-xs text-slate-500">读取短信服务状态…</p>}{capability.data&&!capability.data.sms_enabled&&<Notice>短信服务尚未配置。已有账号可使用密码登录；新用户可使用邮箱注册。</Notice>}{capability.error&&<Notice tone="error">短信状态读取失败 <button type="button" onClick={()=>capability.refetch()}>重试</button></Notice>}{error&&<Notice tone="error">{error}</Notice>}</div>
}

export function Auth(){
 const setToken=useUI(s=>s.setToken)
 const [register,setRegister]=useState(false),[sms,setSMS]=useState(false),[account,setAccount]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[code,setCode]=useState(''),[challenge,setChallenge]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const needCode=sms||(register&&!account.includes('@'))
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await api<{token:string}>(register?'/register':sms?'/auth/sms/login':'/login','','POST',sms?{phone:account,code,challenge_id:challenge}:{account,password,...(register?{name,code,challenge_id:challenge}:{})});setToken(r.token)}catch(e){setError(String(e))}finally{setBusy(false)}}
 return <main className="min-h-screen bg-gradient-to-br from-emerald-50 via-white to-amber-50 px-4 py-16"><div className="mx-auto max-w-md"><div className="mb-8 text-center"><div className="text-5xl">🍲</div><h1 className="mt-3 text-4xl font-bold text-emerald-900">FoodFlow 食光</h1><p className="mt-2 text-slate-600">让家里的食材和每一餐有序流动</p></div><Card className="p-6"><h2 className="mb-5 text-2xl font-bold">{register?'创建账号':'欢迎回来'}</h2><form onSubmit={submit} className="space-y-4">{register&&<Field label="称呼" required value={name} onChange={e=>setName(e.target.value)}/>}<Field label={sms?'手机号':'手机号或邮箱'} type={sms?'tel':'text'} autoComplete="username" required maxLength={254} value={account} onChange={e=>{setAccount(e.target.value);setChallenge('');setCode('')}}/>{!sms&&<Field label="密码" type="password" autoComplete={register?'new-password':'current-password'} minLength={8} required value={password} onChange={e=>setPassword(e.target.value)}/>}<p className="text-xs text-slate-500">绑定到同一账号的手机号与邮箱，共用同一个密码。</p>{needCode&&<SMSCode key={(sms?'login':'register')+account} phone={account} purpose={sms?'login':'register'} onChallenge={setChallenge} code={code} onCode={setCode}/>}{error&&<Notice tone="error">{error}</Notice>}<Button className="w-full" disabled={busy||(needCode&&!challenge)}>{busy?'请稍候…':register?'注册':'登录'}</Button></form>{!register&&<button className="mt-4 w-full text-sm text-emerald-700" onClick={()=>{setSMS(!sms);setChallenge('');setCode('');setError('')}}>{sms?'使用密码登录':'使用短信验证码登录'}</button>}<button className="mt-4 w-full text-sm text-emerald-700" onClick={()=>{setRegister(!register);setSMS(false);setChallenge('');setCode('');setError('')}}>{register?'已有账号？登录':'还没有账号？注册'}</button></Card></div></main>
}

export function PhoneBinding({token}:{token:string}){
 const q=useQueryClient();const me=useQuery({queryKey:['account-phone'],queryFn:()=>api<{phone:string;phone_verified:boolean;email:string}>('/me',token)})
 const [phone,setPhone]=useState(''),[password,setPassword]=useState(''),[code,setCode]=useState(''),[challenge,setChallenge]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false)
 async function bind(e:React.FormEvent){e.preventDefault();setError('');setBusy(true);try{await api('/me/phone',token,'POST',{phone,password,code,challenge_id:challenge});setSaved(true);setPassword('');setCode('');setChallenge('');await q.invalidateQueries()}catch(e){setError(String(e))}finally{setBusy(false)}}
 return <Card className="mt-4"><h2 className="font-semibold">手机号绑定</h2>{me.isLoading?<p>加载中…</p>:me.error?<Notice tone="error">账号读取失败 <Button onClick={()=>me.refetch()}>重试</Button></Notice>:me.data?.phone_verified?<p className="mt-3 text-sm">已验证绑定 {me.data.phone}，可以使用手机号或已绑定邮箱及原密码登录。</p>:<form className="mt-3 space-y-3" onSubmit={bind}><p className="text-xs text-slate-500">验证手机号后添加到当前账号，不会合并其他账号。已有手机号需验证原号码。</p><Field label="手机号（中国大陆 +86）" type="tel" required value={phone} onChange={e=>{setPhone(e.target.value);setCode('');setChallenge('')}}/><Field label="当前账号密码" type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/><SMSCode key={phone} phone={phone} purpose="bind" token={token} onChallenge={setChallenge} code={code} onCode={setCode}/><Button disabled={busy||!challenge}>{busy?'绑定中…':'验证并绑定'}</Button></form>}{saved&&<Notice tone="success">绑定成功，密码保持不变。</Notice>}{error&&<Notice tone="error">{error}</Notice>}</Card>
}
