import {useState} from 'react'
import {useQuery} from '@tanstack/react-query'
import {api} from './api'
import {Button,Card,Notice} from './ui'

import type { components } from './generated/api'
type Report=components['schemas']['NutritionReport']
type Day=Report['daily'][number]
const axes=[{key:'energy',name:'热量',unit:'kcal',ref:2000},{key:'protein',name:'蛋白质',unit:'g',ref:60},{key:'fat',name:'脂肪',unit:'g',ref:60},{key:'carbs',name:'碳水',unit:'g',ref:300},{key:'fiber',name:'膳食纤维',unit:'g',ref:25}] as const
const point=(i:number,r:number)=>`${160+Math.sin(i*2*Math.PI/5)*r},${145-Math.cos(i*2*Math.PI/5)*r}`
const sum=(ds:Day[],key:keyof Day)=>ds.reduce((n,d)=>n+(typeof d[key]==='number'?Number(d[key]):0),0)
export function NutritionRadar({root,token}:{root:string;token:string}){
 const [days,setDays]=useState(7)
 const q=useQuery({queryKey:['nutrition',root,days],queryFn:()=>api<Report>(`${root}/nutrition?days=${days}`,token)})
 const d=q.data,recorded=d?.daily.filter(x=>x.meals>0)||[],knownDays=recorded.filter(x=>x.known_lines>0).length
 const lines=sum(recorded,'lines'),known=sum(recorded,'known_lines'),estimated=sum(recorded,'estimated_lines')
 const confirmed=sum(recorded,'confirmed_mass_lines')
 const values=axes.map(a=>knownDays?sum(recorded,a.key)/recorded.length:null)
 const vegetable=sum(recorded,'vegetable_grams'),dark=sum(recorded,'dark_grams'),unknownVeg=sum(recorded,'unknown_vegetables')
 const darkRatio=vegetable>0&&unknownVeg===0&&known===lines?dark/vegetable:null
 return <Card className="mb-6 overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold">家庭营养雷达</h2><p className="mt-1 text-sm text-slate-500">从已完成餐次，了解餐桌上的营养组成</p></div><div className="flex gap-1 rounded-xl bg-slate-100 p-1">{[7,30].map(n=><Button key={n} size="sm" variant={days===n?'default':'ghost'} aria-pressed={days===n} onClick={()=>setDays(n)}>近 {n} 天</Button>)}</div></div>
 {q.isPending&&<p className="py-8 text-slate-500" role="status">正在汇总烹饪记录…</p>}
 {q.isError&&<div className="mt-4"><Notice tone="error">{String(q.error)} <Button size="sm" onClick={()=>q.refetch()}>重新加载</Button></Notice></div>}
 {d&&<><div className="mt-5 grid grid-cols-3 gap-2 text-center"><div className="rounded-xl bg-emerald-50 p-3"><strong className="block text-xl text-emerald-800">{sum(recorded,'meals')}</strong><span className="text-xs text-slate-600">完成餐次</span></div><div className="rounded-xl bg-emerald-50 p-3"><strong className="block text-xl text-emerald-800">{recorded.length} / {days}</strong><span className="text-xs text-slate-600">有记录的天数</span></div><div className="rounded-xl bg-emerald-50 p-3"><strong className="block text-xl text-emerald-800">{lines?Math.round(100*known/lines)+'%':'—'}</strong><span className="text-xs text-slate-600">消耗条目可计算率</span></div></div>
 {!recorded.length?<div className="py-10 text-center"><p className="text-3xl" aria-hidden>🥗</p><h3 className="mt-3 font-semibold">从一顿家常饭开始</h3><p className="mt-2 text-sm text-slate-500">在「今天」完成烹饪打卡后，这里会汇总食材营养估算。</p></div>:<><div className="grid items-center gap-4 md:grid-cols-2"><svg viewBox="0 0 320 290" className="mx-auto w-full max-w-sm" role="img" aria-label="营养估算与食品标签参考值对比，数值见右侧表格">{[100,75,50,25].map(r=><polygon key={r} points={axes.map((_,i)=>point(i,r)).join(' ')} fill={r===100?'#f0fdf4':'none'} stroke="#cbd5e1"/>)}{axes.map((a,i)=><g key={a.key}><line x1="160" y1="145" x2={point(i,100).split(',')[0]} y2={point(i,100).split(',')[1]} stroke="#cbd5e1"/><text x={point(i,125).split(',')[0]} y={Number(point(i,125).split(',')[1])+4} textAnchor="middle" fontSize="12" fill="#475569">{a.name}</text></g>)}{knownDays>0&&<polygon points={values.map((v,i)=>point(i,Math.min(100,(v||0)/axes[i].ref*100))).join(' ')} fill="#10b98155" stroke="#047857" strokeWidth="2"/>}</svg><div><h3 className="font-semibold">每人 · 记录日均估算</h3><p className="my-2 text-xs text-slate-500">按各餐打卡时的份数均分，仅统计已记录食材。</p><table className="w-full text-sm"><thead><tr className="text-left text-xs text-slate-500"><th className="py-2">营养素</th><th>估算量</th><th>标签参考比</th></tr></thead><tbody>{axes.map((a,i)=><tr key={a.key} className="border-t border-slate-100"><td className="py-2">{a.name}</td><td>{values[i]===null?'—':values[i]!.toFixed(1)+' '+a.unit}</td><td>{values[i]===null?'—':Math.round(values[i]!/a.ref*100)+'%'}</td></tr>)}</tbody></table></div></div>
 <div className="space-y-2">{confirmed>0&&<p className="text-xs text-slate-500">{confirmed} 条消耗使用当时已确认的批次可食重量换算。</p>}{known<lines&&<Notice>部分食材尚不能换算：当前数值仅代表已知部分，不能判断全天摄入是否充足。</Notice>}{estimated>0&&<Notice>包含 {estimated} 条免称重估计消耗，未代表真实称重。</Notice>}{recorded.some(x=>x.protein_low_streak)&&<Notice>有连续三天的三餐记录中，蛋白质估算低于标签参考值。请先核对漏记、份数与外食记录，再考虑调整搭配。</Notice>}{darkRatio!==null?<Notice>已记录蔬菜中，深色蔬菜重量占比 {Math.round(darkRatio*100)}%。{darkRatio<0.3?'低于项目 30% 提醒线，可增加菠菜、西兰花等搭配。':'保持食材种类多样。'}</Notice>:<p className="text-xs text-slate-500">深色蔬菜占比：数据或品种分类不足，暂不评价。</p>}</div>
 <details className="mt-4 text-sm"><summary className="cursor-pointer font-medium">每日记录与未计入项</summary><div className="mt-3 max-h-64 overflow-auto"><table className="w-full text-sm"><thead><tr className="text-left"><th>日期</th><th>餐次</th><th>人均热量估算</th></tr></thead><tbody>{d.daily.map(x=><tr key={x.day} className="border-t border-slate-100"><td className="py-2">{x.day.slice(5)}</td><td>{x.meals||'未记录'}</td><td>{x.energy===null?'—':x.energy.toFixed(1)+' kcal'}</td></tr>)}</tbody></table></div>{d.excluded.map(x=><p className="mt-2 text-xs text-amber-800" key={x.name+x.unit+x.reason}>{x.name}（{x.unit}）：{x.reason}</p>)}</details></>}
 <details className="mt-4 border-t border-slate-100 pt-3 text-xs leading-6 text-slate-500"><summary className="cursor-pointer">计算口径与来源</summary><p>原料消耗量 × 每100克参考营养组成，按餐次历史份数均分，再除以有记录的天数。没有记录的日期不按零摄入计算。已确认批次按称量样本的可食净重比例换算；未确认的 g/kg 暂按原料重量估算，按个、体积计量且没有质量换算的食材不计入；烹饪损耗、可食部比例、剩菜和个人分餐差异尚未测量，因此不等于实际摄入。</p><p>营养组成来自打卡时保存的 USDA SR Legacy 2018 参考快照；旧记录缺少快照不回填。雷达外圈为标签参考值的100%，超过部分仅图形截断。百分比越高不代表越健康；不生成医学健康评分。</p><p><a className="underline" target="_blank" rel="noreferrer" href="https://www.nhc.gov.cn/ewebeditor/uploadfile/2013/06/20130605104041625.pdf">GB 28050—2011 附录 A</a>：2000 kcal、蛋白质60g、脂肪60g、碳水300g、纤维25g，仅用于对比，不是个体饮食处方。深色蔬菜30%为项目提醒线；<a className="underline" target="_blank" rel="noreferrer" href="https://www.nhc.gov.cn/sps/c100088/202505/6b7a718abd4848e8a3e98fc561a8858b.shtml">国家卫健委饮食核心信息</a>建议深色蔬菜占一半以上。</p></details></>}
 </Card>
}
